name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: "mix test (otp-${{matrix.otp}}, elixir-${{matrix.elixir}})"
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        include:
          - elixir: 1.12.3
            otp: 24.3

          - elixir: 1.13.4
            otp: 24.3

          - elixir: 1.13.4
            otp: 25.3

          - elixir: 1.14.3
            otp: 24.3

          - elixir: 1.14.3
            otp: 25.3

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test
